"""from_id and to_id changed to from_name and to_name

Revision ID: 6d85e3ff333a
Revises: 8e881204c056
Create Date: 2025-07-18 23:05:59.031104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d85e3ff333a'
down_revision: Union[str, Sequence[str], None] = '8e881204c056'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('join_requests', sa.Column('from_name', sa.String(), nullable=True))
    op.add_column('join_requests', sa.Column('to_name', sa.String(), nullable=True))
    op.drop_constraint(op.f('join_requests_to_id_group_name_key'), 'join_requests', type_='unique')
    op.create_unique_constraint(None, 'join_requests', ['to_name', 'group_name'])
    op.drop_constraint(op.f('join_requests_from_id_fkey'), 'join_requests', type_='foreignkey')
    op.drop_constraint(op.f('join_requests_to_id_fkey'), 'join_requests', type_='foreignkey')
    op.create_foreign_key(None, 'join_requests', 'users', ['from_name'], ['name'], ondelete='CASCADE')
    op.create_foreign_key(None, 'join_requests', 'users', ['to_name'], ['name'], ondelete='CASCADE')
    op.drop_column('join_requests', 'to_id')
    op.drop_column('join_requests', 'from_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('join_requests', sa.Column('from_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('join_requests', sa.Column('to_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'join_requests', type_='foreignkey')
    op.drop_constraint(None, 'join_requests', type_='foreignkey')
    op.create_foreign_key(op.f('join_requests_to_id_fkey'), 'join_requests', 'users', ['to_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('join_requests_from_id_fkey'), 'join_requests', 'users', ['from_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'join_requests', type_='unique')
    op.create_unique_constraint(op.f('join_requests_to_id_group_name_key'), 'join_requests', ['to_id', 'group_name'], postgresql_nulls_not_distinct=False)
    op.drop_column('join_requests', 'to_name')
    op.drop_column('join_requests', 'from_name')
    # ### end Alembic commands ###
