"""Foreign key to group chaged to grou _name from group_id

Revision ID: 8e881204c056
Revises: ea7ffa5dec6e
Create Date: 2025-07-18 22:47:57.919768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e881204c056'
down_revision: Union[str, Sequence[str], None] = 'ea7ffa5dec6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('join_requests', sa.Column('group_name', sa.String(), nullable=True))
    op.drop_constraint(op.f('join_requests_to_id_from_id_key'), 'join_requests', type_='unique')
    op.create_unique_constraint(None, 'join_requests', ['to_id', 'group_name'])
    op.drop_constraint(op.f('join_requests_group_id_fkey'), 'join_requests', type_='foreignkey')
    op.create_foreign_key(None, 'join_requests', 'groups', ['group_name'], ['name'], ondelete='CASCADE')
    op.drop_column('join_requests', 'group_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('join_requests', sa.Column('group_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'join_requests', type_='foreignkey')
    op.create_foreign_key(op.f('join_requests_group_id_fkey'), 'join_requests', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'join_requests', type_='unique')
    op.create_unique_constraint(op.f('join_requests_to_id_from_id_key'), 'join_requests', ['to_id', 'from_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('join_requests', 'group_name')
    # ### end Alembic commands ###
