"""group changed to group_id in AgentMessage

Revision ID: b284448a1a02
Revises: bf1716bcfcfd
Create Date: 2025-07-24 23:11:34.694333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b284448a1a02'
down_revision: Union[str, Sequence[str], None] = 'bf1716bcfcfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_messages', sa.Column('group_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('model_messages_group_fkey'), 'model_messages', type_='foreignkey')
    op.create_foreign_key(None, 'model_messages', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.drop_column('model_messages', 'group')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_messages', sa.Column('group', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'model_messages', type_='foreignkey')
    op.create_foreign_key(op.f('model_messages_group_fkey'), 'model_messages', 'groups', ['group'], ['id'], ondelete='CASCADE')
    op.drop_column('model_messages', 'group_id')
    # ### end Alembic commands ###
