"""one-to-many relation added to group and message

Revision ID: bd151d290a76
Revises: 71d8bd2314b7
Create Date: 2025-07-23 23:18:32.954428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd151d290a76'
down_revision: Union[str, Sequence[str], None] = '71d8bd2314b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('human_messages', sa.Column('group', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'human_messages', 'groups', ['group'], ['id'], ondelete='CASCADE')
    op.add_column('model_messages', sa.Column('group', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'model_messages', 'groups', ['group'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'model_messages', type_='foreignkey')
    op.drop_column('model_messages', 'group')
    op.drop_constraint(None, 'human_messages', type_='foreignkey')
    op.drop_column('human_messages', 'group')
    # ### end Alembic commands ###
