"""user and messages, and agent and messages,relationship maintained

Revision ID: bf1716bcfcfd
Revises: cdaf0db79311
Create Date: 2025-07-24 22:42:12.002134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf1716bcfcfd'
down_revision: Union[str, Sequence[str], None] = 'cdaf0db79311'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('human_messages', sa.Column('user_id', sa.UUID(), nullable=True))
    op.add_column('human_messages', sa.Column('group_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('human_messages_group_and_crpnd_user_fkey'), 'human_messages', type_='foreignkey')
    op.drop_constraint(op.f('human_messages_group_fkey'), 'human_messages', type_='foreignkey')
    op.create_foreign_key(None, 'human_messages', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'human_messages', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('human_messages', 'group')
    op.drop_column('human_messages', 'group_and_crpnd_user')
    op.add_column('model_messages', sa.Column('agent_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('model_messages_group_and_crpnd_agent_fkey'), 'model_messages', type_='foreignkey')
    op.create_foreign_key(None, 'model_messages', 'ai_agents', ['agent_id'], ['id'], ondelete='CASCADE')
    op.drop_column('model_messages', 'group_and_crpnd_agent')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_messages', sa.Column('group_and_crpnd_agent', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'model_messages', type_='foreignkey')
    op.create_foreign_key(op.f('model_messages_group_and_crpnd_agent_fkey'), 'model_messages', 'group_and_agent_associations', ['group_and_crpnd_agent'], ['id'], ondelete='CASCADE')
    op.drop_column('model_messages', 'agent_id')
    op.add_column('human_messages', sa.Column('group_and_crpnd_user', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('human_messages', sa.Column('group', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'human_messages', type_='foreignkey')
    op.drop_constraint(None, 'human_messages', type_='foreignkey')
    op.create_foreign_key(op.f('human_messages_group_fkey'), 'human_messages', 'groups', ['group'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('human_messages_group_and_crpnd_user_fkey'), 'human_messages', 'group_and_user_association', ['group_and_crpnd_user'], ['id'], ondelete='CASCADE')
    op.drop_column('human_messages', 'group_id')
    op.drop_column('human_messages', 'user_id')
    # ### end Alembic commands ###
