"""Secont update to models

Revision ID: ea7ffa5dec6e
Revises: d5ed712a0d18
Create Date: 2025-07-15 03:25:22.823858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea7ffa5dec6e'
down_revision: Union[str, Sequence[str], None] = 'd5ed712a0d18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('group_and_user_association_group_id_fkey'), 'group_and_user_association', type_='foreignkey')
    op.drop_constraint(op.f('group_and_user_association_user_id_fkey'), 'group_and_user_association', type_='foreignkey')
    op.create_foreign_key(None, 'group_and_user_association', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'group_and_user_association', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('groups_admin_user_fkey'), 'groups', type_='foreignkey')
    op.create_foreign_key(None, 'groups', 'users', ['admin_user'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('human_messages_group_and_crpnd_user_fkey'), 'human_messages', type_='foreignkey')
    op.create_foreign_key(None, 'human_messages', 'group_and_user_association', ['group_and_crpnd_user'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('join_requests_to_id_fkey'), 'join_requests', type_='foreignkey')
    op.drop_constraint(op.f('join_requests_group_id_fkey'), 'join_requests', type_='foreignkey')
    op.drop_constraint(op.f('join_requests_from_id_fkey'), 'join_requests', type_='foreignkey')
    op.create_foreign_key(None, 'join_requests', 'users', ['from_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'join_requests', 'users', ['to_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'join_requests', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('model_messages_group_and_crpnd_agent_fkey'), 'model_messages', type_='foreignkey')
    op.create_foreign_key(None, 'model_messages', 'group_and_agent_associations', ['group_and_crpnd_agent'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'model_messages', type_='foreignkey')
    op.create_foreign_key(op.f('model_messages_group_and_crpnd_agent_fkey'), 'model_messages', 'group_and_agent_associations', ['group_and_crpnd_agent'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'join_requests', type_='foreignkey')
    op.drop_constraint(None, 'join_requests', type_='foreignkey')
    op.drop_constraint(None, 'join_requests', type_='foreignkey')
    op.create_foreign_key(op.f('join_requests_from_id_fkey'), 'join_requests', 'users', ['from_id'], ['id'])
    op.create_foreign_key(op.f('join_requests_group_id_fkey'), 'join_requests', 'groups', ['group_id'], ['id'])
    op.create_foreign_key(op.f('join_requests_to_id_fkey'), 'join_requests', 'users', ['to_id'], ['id'])
    op.drop_constraint(None, 'human_messages', type_='foreignkey')
    op.create_foreign_key(op.f('human_messages_group_and_crpnd_user_fkey'), 'human_messages', 'group_and_user_association', ['group_and_crpnd_user'], ['id'])
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.create_foreign_key(op.f('groups_admin_user_fkey'), 'groups', 'users', ['admin_user'], ['id'])
    op.drop_constraint(None, 'group_and_user_association', type_='foreignkey')
    op.drop_constraint(None, 'group_and_user_association', type_='foreignkey')
    op.create_foreign_key(op.f('group_and_user_association_user_id_fkey'), 'group_and_user_association', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('group_and_user_association_group_id_fkey'), 'group_and_user_association', 'groups', ['group_id'], ['id'])
    # ### end Alembic commands ###
